### ISSUE TITLE
Nexus not Authorised

### ISSUE THREAD

**Issue by pmbsa** [egineering-llc/gitflow-helper-maven-plugin#37]
Hi, I seem to have a small issue when running builds against master

Failed to execute goal com.e-gineering:gitflow-helper-maven-plugin:1.4.0:promote-master (default) on project SpidaParent: Could not locate artifact catalog in remote repository. Could not transfer artifact com.spidasolutions.mvn:TestPom:txt:catalog:0.1 from/to stage (http://spidanexus/nexus/repository/maven-staging/): Not authorized , ReasonPhrase:Unauthorized. -

When I look at nexus logs I can see the following which makes me think an anon login has happened.

[qtp1580987159-884] *UNKNOWN org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
2016-08-23 12:43:54,259+0000 INFO  [qtp1580987159-884] *UNKNOWN org.sonatype.nexus.security.internal.AnonymousManagerImpl - Loaded configuration: AnonymousConfiguration{enabled=false, userId='anonymous', realmName='NexusAuthorizingRealm'}
2016-08-23 12:58:03,940+0000 WARN  [qtp1580987159-174] *UNKNOWN org.apache.shiro.mgt.DefaultSecurityManager - Delegate RememberMeManager instance of type [org.apache.shiro.nexus.NexusCookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.crypto.CryptoException: Unable to execute 'doFinal' with cipher instance [javax.crypto.Cipher@6884fa6].

my pom config is

```
            <plugin>
                    <groupId>com.e-gineering</groupId>
                    <artifactId>gitflow-helper-maven-plugin</artifactId>
                    <version>1.4.0</version>
                    <configuration>
                        <releaseDeploymentRepository>release::default::${release.url}::false</releaseDeploymentRepository>
                        <stageDeploymentRepository>stage::default::${stage.url}::true</stageDeploymentRepository>
                        <snapshotDeploymentRepository>snapshots::default::${snapshots.url}::true</snapshotDeploymentRepository>
                </configuration>
                <extensions>true</extensions>
                <executions>
                        <execution>
                            <goals>
                                    <goal>enforce-versions</goal>
                                    <goal>retarget-deploy</goal>
                                    <goal>tag-master</goal>
                                    <goal>promote-master</goal>
                            </goals>
                        </execution>
                </executions>
            </plugin>
```

and in my settings I have the following to support that

```
<server>
  <id>snapshots</id>
  <username>user</username>
  <password>mypassword</password>
</server>
<server>
  <id>release</id>
  <username>user</username>
  <password>mypassword</password>
</server>
<server>
  <id>stage</id>
  <username>user</username>
  <password>mypassword</password>
</server>


    <properties>
            <release.url>http://spidanexus/nexus/repository/maven-releases/</release.url>
            <snapshots.url>http://spidanexus/nexus/repository/maven-snapshots/</snapshots.url>
            <stage.url>http://spidanexus/nexus/repository/maven-staging/</stage.url>
    </properties>
```

I cant see why the login would be anon but I am hoping you might have some insight? 

regards
Paul

**Comment by pmbsa** [comment]
Ignore the nexus log output, I dont think thats relevent to this at all.
thanks
Paul

**Comment by bvarner** [comment]
Hmmm.

Could it be the trailing '/' on the end of your URLs?


In my setups, we're using the same nexus user on the same nexus server for all our repos, so I have the same id portion of my releases.
But I doubt that's the issue.

**Comment by pmbsa** [comment]
Tried that, made no difference. the only thing that works is if I allow anon access to the nexus repo. Then it works fine

**Comment by bvarner** [comment]
Have you tried setting up your repository definition exactly like you did release -- with the final boolean value (the uniqueVersion portion) set to "false"? All of my setups use this pattern, since the point of the stage repository is to provide a place for versioned artifacts to be staged for testing, and once proven proper, that single artifact promoted to production.

Having uniqueVersion set to true on snapshots will break those semantics, and very well may contribute to the issues you're seeing.

**Comment by bvarner** [comment]
Any chance in having a retest now, @pmbsa ?

**Comment by pmbsa** [comment]
Hi, apologies, yes I have setup the staging repo exactly as suggested but the issue remains... I have subsequently learned that nexus 3 is very different from nexus 2. Is that possibly the root cause here?

**Comment by Fochest** [comment]
Hey, I am running into the same problem here. Repository configuration is exactly as proposed here (unique on stage to false).

        <configuration>
          <releaseDeploymentRepository>
            nexus::default::https://nexus/content/repositories/releases::false
          </releaseDeploymentRepository>
          <stageDeploymentRepository>
            nexus::default::https://nexus/content/repositories/stage::false
          </stageDeploymentRepository>
          <snapshotDeploymentRepository>
            nexus::default::https://nexus/content/repositories/snapshots::true
          </snapshotDeploymentRepository>
        </configuration>

Deployment to stage repository works but during the promote-master phase the retrieval of the catalog seems to be unauthorized.

[ERROR] Failed to execute goal com.e-gineering:gitflow-helper-maven-plugin:1.5.0:promote-master (default) on project project: Could not locate artifact catalog in remote repository. Could not transfer artifact groupId:artifactId:txt:catalog:1.0.7 from/to nexus (https://nexus/content/repositories/stage): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1] 

Maven 3.3.9
gitflow-helper-maven-plugin:1.5.0
Nexus: 2.12.1-01, anonymous access disabled
Jenkins: 2.33, settings.xml contains the <servers><server><id>nexus</id>... part, also the global configuration does (just to be sure). 

If you need more information, please let me know.

**Comment by bvarner** [comment]
Wanted to commend on this publicly, because I do realize the importance of this PR, and this issue.

I'm in the process today of testing this out and working through things. I'd like to get it in today, but I don't want to promise anything concrete. I'm thrilled someone was able to figure this out and contribute, and I don't want to dissuade further contributions by taking too long to merge.

When will then be now?

Soon.
