### ISSUE TITLE
tag-master goal unable to push to BitBucket

### ISSUE THREAD

**Issue by xlebec** [egineering-llc/gitflow-helper-maven-plugin#43]
When merging branches into master with the tag-master goal enabled I get:

```
[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/myProject/workspace && git push http:********@git.myServer.com/myProject.git refs/tags/0.0.37
[INFO] Working directory: /var/lib/jenkins/jobs/myProject/workspace
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] fatal: could not read Password for 'http://jenkins@git.myServer.com': No such device or address
```

In addition to the gitflow-helper-maven-plugin my pom.xml I also has:

```
<project.scm.id>myServerId</project.scm.id>
...
<scm>
    <connection>scm:git:http://jenkins@git.myServer.com/scm/myProject.git</connection>
    <developerConnection>scm:git:http://jenkins@git.myServer.com/scm/myProject.git</developerConnection>
    <tag>HEAD</tag>
</scm>
```

and in the settings.xml of the docker container running Jenkins I have:

```
<servers>
    <server>
        <id>myServerId</id>
        <username>jenkins</username>
        <password>myPassword</password>
    </server>
    ...
</servers>
```

I notice that when I use the maven-release-plugin my git push looks more like:
`[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/myProject/workspace && git push http://jenkins:********@git.myServer.com/scm/myProject.git refs/tags/0.0.37`
that is to say, it has "//jenkins:" after the username. I'm guessing that somehow my username and password from the settings.xml is not being added to the push request when using gitflow-helper-maven-plugin.

**Comment by bvarner** [comment]
Do you have the jenkins job set to use the settings.xml from the filesystem, rather than the built-in jenkins 'global settings xml'?

**Comment by xlebec** [comment]
Thanks for the response. It is currently set to "Use default maven settings", and the settings file containing the <sever> configuration is in ${user.home}/.m2/settings.xml.

**Comment by raehalme** [comment]
I'm having the same trouble when running the build on Atlassian Bamboo. 

It looks like the provided Git URL is never used although it is being set as the developerConnectionUrl. The reason is that the connectionType is not being set as "developerConnection" but has the default value of "connection".

Here is some output from the Maven run on the Bamboo agent:

```
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-scm-plugin:1.9.4:tag' with basic configurator -->
[DEBUG]   (f) tag = V1.1
[DEBUG]   (f) developerConnectionUrl = scm:git:scm:git:ssh://git@xxx/yyy/zzz.git
[DEBUG]   (f) addTimestamp = false
[DEBUG]   (f) basedir = /var/atlassian/bamboo-agent-home/xml-data/build-dir/xxx
[DEBUG]   (f) connectionType = connection
[DEBUG]   (s) connectionUrl = scm:git:https://xxx/yyy/zzz.git
[DEBUG]   (f) pushChanges = true
[DEBUG]   (f) remoteTagging = true
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@64a1923a
[DEBUG]   (f) timestampFormat = yyyyMMddHHmmss
[DEBUG]   (f) timestampPosition = end
[DEBUG]   (f) timestampPrefix = -
[DEBUG] -- end configuration --
[INFO] Final Tag Name: 'V1.1'
[INFO] Executing: /bin/sh -c cd /var/atlassian/bamboo-agent-home/xml-data/build-dir/xxx && git tag -F /tmp/xxx/maven-scm-493794421.commit V1.1
[INFO] Working directory: /var/atlassian/bamboo-agent-home/xml-data/build-dir/xxx
[INFO] Executing: /bin/sh -c cd /var/atlassian/bamboo-agent-home/xml-data/build-dir/xxx && git push https://xxx/yyy/zzz.git refs/tags/V1.1
[INFO] Working directory: /var/atlassian/bamboo-agent-home/xml-data/build-dir/xxx
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] fatal: could not read Username for 'https://xxx': No such device or address
``` 

I think the correct fix would be to add element `connection` with value `developerConnection` to the SCM plugin configuration.

**Comment by bvarner** [comment]
Thanks @raehalme! If you'd like to submit a PR for this, I'd be happy to review.

Otherwise, it could be a week or so before I get a chance to look at it.

**Comment by raehalme** [comment]
One PR coming right up :-)

**Comment by bvarner** [comment]
1.5.2 is out in nexus central. Thanks @raehalme for the assist on this one!

**Comment by raehalme** [comment]
That's awesome! Thank you for the quick response and what looks to me a great plugin!
