### ISSUE TITLE
Detect current branch name without external dependencies

### ISSUE THREAD

**Issue by raehalme** [egineering-llc/gitflow-helper-maven-plugin#52]
I would appreciate if this great plugin could resolve the current Git branch name without external dependencies. I'm not too happy about modifying our CI agents to set environment variables as I would like to configuration to be kept as simple and clean as possible.

One solution is to use the plugin `org.codehaus.mojo:buildnumber-maven-plugin` which is capable of setting the current branch name into a property (by default `scmBranch`). This property can be referenced in the `gitBranchExpression` property as long as the plugin is allowed to be executed.

Would you be willing to consider adding the plugin `org.codehaus.mojo:buildnumber-maven-plugin` to the set of retained plugins?

Would it make sense to make the list of retained plugins to be configurable? It would allow other similar plugins to be easily configured as well.

**Comment by raehalme** [comment]
Actually after testing this by retaining also the `buildnumber-maven-plugin` plugin the process no longer runs as intended. For example, test and compile are now again included in the build process.

It would probably be best if the branch name could be resolved without the help of any other plugins (to avoid them messing up the build process). I'll have a look if we could easily incorporate the logic in `buildnumber-maven-plugin` to resolve the current branch directly in this plugin.

**Comment by raehalme** [comment]
I now have a version available which uses `ScmManager` and the Git provider to resolve the current branch name. Would it be okay to replace the default value `${env.GIT_BRANCH}` with this implementation? You could still specify `${env.GIT_BRANCH}` explicitly in the configuration, if preferred.

**Comment by bvarner** [comment]
Interesting. I'd be curious to see a pull request!

The reason I used '${env.GIT_BRANCH}' was that it was (hah provided) by my CI server (Jenkins), and easy to detect if it wasn't set at all (in a local developer environment)

**Comment by raehalme** [comment]
Sure thing! Should I target the development branch? Looks like it's a bit out of date, could you maybe update it?

**Comment by bvarner** [comment]
Looks like I'd managed to forget to push my local merges. Whoops!

Should be all up to date now.

**Comment by raehalme** [comment]
Thanks! You can see my changes in https://github.com/egineering-llc/gitflow-helper-maven-plugin/pull/53.

**Comment by bvarner** [comment]
So what's funny, is that you probably could have just put..

`<gitBranchExpression>${project.scm.developerConnection</gitBranchExpression>` and just ignored all the code changes. :-D ohhhh I wish I'd thought of that sooner.

**Comment by raehalme** [comment]
Are you sure about that? Must be some weird Maven magic behind the scenes
then :-)




On Feb 2, 2017 20:22, "Bryan Varner" <notifications@github.com> wrote:

So what's funny, is that you probably could have just put..

<gitBranchExpression>${project.scm.developerConnection</gitBranchExpression>
and just ignored all the code changes. :-D ohhhh I wish I'd thought of that
sooner.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/egineering-llc/gitflow-helper-maven-plugin/issues/52#issuecomment-277039080>,
or mute the thread

**Comment by bvarner** [comment]
Yeah, it wouldn't have worked for the branch name. :-)
