### ISSUE TITLE
Deploy develop branch to Nexus

### ISSUE THREAD

**Issue by diablox3m** [egineering-llc/gitflow-helper-maven-plugin#55]
Hi,

First of all, thanks for the plugin, it's great and really helpful. 

I'm having a problem with building a develop branch. I'm using all the default settings from your instructions, and everything works fine (builds, release and master branches deployment, etc.) except deploying a build artifact (SNAPSHOT) from the develop branch. It's built properly but newer deployed to the Nexus snapshot repository.

This is the message from the maven output (at least relevant part):
[INFO] --- gitflow-helper-maven-plugin:1.5.2:retarget-deploy (default) @ springboot-adminlte-security ---
[INFO] Un-Setting artifact repositories.
[INFO] Setting maven.deploy.skip = 'true'

There are no any errors, it just never gets deployed after the build is successful.

Thanks for the help in advance.

**Comment by diablox3m** [comment]
Hi,

Please ignore my previous question. I've found what's causing a problem. My development branch is called origin/develop and default pattern is origin/development :).

Thanks again for this great plugin!

Regards,
Branko

**Comment by bvarner** [comment]
I was looking over this yesterday and starting to wonder if that was the issue.

I think we've had a recommendation to make the defaults more in-line with the default 'gitflow' naming scheme, and I think that would make a lot of sense.

The strange naming system we have (for the develop branch name) is an artifact of a highly-opinionated viewpoint being imposed. ;-)

**Comment by diablox3m** [comment]
Thanks a lot!
