### ISSUE TITLE
enforce-versions does not work

### ISSUE THREAD

**Issue by burtsevyg** [egineering-llc/gitflow-helper-maven-plugin#56]
Sorry, but I can not correctly configure gitflow-helper or it is a bug.
My pom.xml look like:
```
    <build>
        <plugins>
            <plugin>
                <groupId>com.e-gineering</groupId>
                <artifactId>gitflow-helper-maven-plugin</artifactId>
                <version>1.5.2</version>
                <extensions>true</extensions>
                <configuration>

                    <releaseDeploymentRepository>${release.repository}</releaseDeploymentRepository>
                    <stageDeploymentRepository>${stage.repository}</stageDeploymentRepository>
                    <snapshotDeploymentRepository>${snapshot.repository}</snapshotDeploymentRepository>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>enforce-versions</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

In master branch I have SNAPSHOT version and in development branch release.
Builds not failed in Jenkins. 
For master Maven log say that:
```
...
Build Extension Resolved: ${env.GIT_BRANCH} to: ${env.GIT_BRANCH}
...
Storing buildScmBranch: origin/master
...
```

In Jenkinsfile:
`echo "${env.BRANCH_NAME}"`
say
master
than
```
            checkout([$class    : 'GitSCM',
                      branches  : [[name: "*/${env.BRANCH_NAME}"]],
                      extensions: [[$class: 'CleanCheckout'],
                                   [$class     : 'LocalBranch',
                                    localBranch: "${env.BRANCH_NAME}"]]])

            stage 'maven build'
            sh "mvn clean package"
```
Experiments with branch pattern for development branch:
in pom.xml
`<developmentBranchPattern>(.*)develop(.*)</developmentBranchPattern>`

```
[DEBUG]   (f) developmentBranchPattern = (.*)develop(.*)
[DEBUG]   (f) hotfixBranchPattern = origin/hotfix/(.*)
[DEBUG]   (f) masterBranchPattern = origin/master
[DEBUG]   (f) releaseBranchPattern = origin/release/(.*)
...
[DEBUG] Resolved gitBranchExpression: '${env.GIT_BRANCH} to '${env.GIT_BRANCH}'
[DEBUG] Building for GitBranchType: UNDEFINED. gitBranch: '${env.GIT_BRANCH}' branchPattern: 'null'

```

I cannot understand where is a problem.

**Comment by bvarner** [comment]
Do you happen to be running on windows?

**Comment by burtsevyg** [comment]
Thank you very mach for response!
I change versions in master and develop for check plugin.
How configure plugin for resolving branch name in Jenkins correctly?

**Comment by bvarner** [comment]
Is your jenkins server running on windows?

**Comment by burtsevyg** [comment]
Using jenkins docker plugin via instruction in Jenkinsfile:
`docker.inside(<my image based on **ubuntu 14.04**>)`
this image have git installed.
Inside this block I check variable ${env.GIT_BRANCH}
`echo ${env.GIT_BRANCH}`
print branch name in format:
"master" or "develop".
Also I have changed branch pattern in pom.xml, but this have no effect.
Sorry for my bad English =(

**Comment by bvarner** [comment]
I just found a spot in the code, where the SNAPSHOT wasn't being enforced on 'develop' branches.

Does that sound like the issue you're having?

You could also try a developmentBranchPattern of
```
(origin/)?develop
```
Which is what I'm currently testing in the 1.6.0-SNAPSHOT which I'm working toward a release on.

**Comment by bvarner** [comment]
Yep. It's out there in central. Give it a shot and let's see if it works. :-)
