### ISSUE TITLE
plugin fails to detect git branch when scm is not defined

### ISSUE THREAD

**Issue by caio2k** [egineering-llc/gitflow-helper-maven-plugin#81]
Hello,

Thanks for developing this plugin. It is very useful in many scenarios.
I've found an issue in the latest version **1.7.2**. When the SCM is not defined in pom.xml the plugin fails to detect the git branch. Simply by defining it it works. 
`    <scm>
        <developerConnection>scm:git:https://XXX</developerConnection>
    </scm>`
In several use cases the SCM is not really required and I think it should be optional. The error line is below:
`[INFO] gitflow-helper-maven-plugin: Build Extension resolved gitBranchExpression: ${env.GIT_BRANCH} to: ${env.GIT_BRANCH}`
edit: fixed version

**Comment by bvarner** [comment]
Agreed. Pull Request #84 addresses this. It allows you to run up through the verify phase without errors, but will block deployment when it cannot resolve a git branch.

This will be released with 1.8.0, which is dropping *soon*.
