### ISSUE TITLE
Support for OneFlow variety of release management

### ISSUE THREAD

**Issue by snowe2010** [egineering-llc/gitflow-helper-maven-plugin#98]
I feel like it's probably possible to handle this with the current flag commands, but I'm not entirely sure how. We're currently using this plugin, but need to switch to a simpler alternative, hence we'd like to do OneFlow. This means we just tag each release/support branch when they end, merging them back to develop (no master branch essentially). Is this currently possible? I feel like I just need to do something like this, but I'm not sure if it will accomplish what I want. 

```
➜ mvn -s ~/.m2/release-settings.xml -DbuildScmBranch=master -Dtag=0.5.0 -DgitURLExpression=git@github.com:blah/blah.git -DgitBranchExpression=release/0.5.0 -DmasterBranchPattern=release/0.5.0 clean deploy
```

**Comment by bvarner** [comment]
That seems kinda close, but in that case, it would probably be better to introduce a new one-flow specific goal that would do the artifact promotion and tagging on the release / support / hotfix branch and ignore the master.

**Comment by snowe2010** [comment]
@bvarner hm do you have any suggestion on how to do that?
